[build]
  command = "npm ci && npm run build"
  publish = "encrypted"

[context.production.environment]
  PAGECRYPT_PW = "$PAGECRYPT_PW"   # set this in Netlify UI → Site Settings → Build & deploy → Environment
