[build]
  command   = "npm ci && npm run build"
  publish   = "public"

[context.production.environment]
  # define your passphrase as an env var in Netlify UI
  PAGECRYPT_PASSWORD = "$PAGECRYPT_PASSWORD"
